// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	models "github.com/milansax96/movie-terminal-api/internal/models"
	tmdb "github.com/milansax96/movie-terminal-api/pkg/tmdb"
	mock "github.com/stretchr/testify/mock"
)

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// DiscoverByGenre provides a mock function with given fields: genreID, page
func (_m *MockAPI) DiscoverByGenre(genreID int, page int) ([]models.Movie, error) {
	ret := _m.Called(genreID, page)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverByGenre")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Movie, error)); ok {
		return rf(genreID, page)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Movie); ok {
		r0 = rf(genreID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(genreID, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_DiscoverByGenre_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverByGenre'
type MockAPI_DiscoverByGenre_Call struct {
	*mock.Call
}

// DiscoverByGenre is a helper method to define mock.On call
//   - genreID int
//   - page int
func (_e *MockAPI_Expecter) DiscoverByGenre(genreID interface{}, page interface{}) *MockAPI_DiscoverByGenre_Call {
	return &MockAPI_DiscoverByGenre_Call{Call: _e.mock.On("DiscoverByGenre", genreID, page)}
}

func (_c *MockAPI_DiscoverByGenre_Call) Run(run func(genreID int, page int)) *MockAPI_DiscoverByGenre_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockAPI_DiscoverByGenre_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_DiscoverByGenre_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_DiscoverByGenre_Call) RunAndReturn(run func(int, int) ([]models.Movie, error)) *MockAPI_DiscoverByGenre_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredits provides a mock function with given fields: mediaType, id
func (_m *MockAPI) GetCredits(mediaType string, id int) (*tmdb.CreditsResponse, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredits")
	}

	var r0 *tmdb.CreditsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*tmdb.CreditsResponse, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *tmdb.CreditsResponse); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.CreditsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredits'
type MockAPI_GetCredits_Call struct {
	*mock.Call
}

// GetCredits is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockAPI_Expecter) GetCredits(mediaType interface{}, id interface{}) *MockAPI_GetCredits_Call {
	return &MockAPI_GetCredits_Call{Call: _e.mock.On("GetCredits", mediaType, id)}
}

func (_c *MockAPI_GetCredits_Call) Run(run func(mediaType string, id int)) *MockAPI_GetCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockAPI_GetCredits_Call) Return(_a0 *tmdb.CreditsResponse, _a1 error) *MockAPI_GetCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetCredits_Call) RunAndReturn(run func(string, int) (*tmdb.CreditsResponse, error)) *MockAPI_GetCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieDetails provides a mock function with given fields: mediaType, id
func (_m *MockAPI) GetMovieDetails(mediaType string, id int) (*tmdb.MovieDetail, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieDetails")
	}

	var r0 *tmdb.MovieDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*tmdb.MovieDetail, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *tmdb.MovieDetail); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.MovieDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetMovieDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieDetails'
type MockAPI_GetMovieDetails_Call struct {
	*mock.Call
}

// GetMovieDetails is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockAPI_Expecter) GetMovieDetails(mediaType interface{}, id interface{}) *MockAPI_GetMovieDetails_Call {
	return &MockAPI_GetMovieDetails_Call{Call: _e.mock.On("GetMovieDetails", mediaType, id)}
}

func (_c *MockAPI_GetMovieDetails_Call) Run(run func(mediaType string, id int)) *MockAPI_GetMovieDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockAPI_GetMovieDetails_Call) Return(_a0 *tmdb.MovieDetail, _a1 error) *MockAPI_GetMovieDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetMovieDetails_Call) RunAndReturn(run func(string, int) (*tmdb.MovieDetail, error)) *MockAPI_GetMovieDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetNowPlaying provides a mock function with given fields: page
func (_m *MockAPI) GetNowPlaying(page int) ([]models.Movie, error) {
	ret := _m.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for GetNowPlaying")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Movie, error)); ok {
		return rf(page)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Movie); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetNowPlaying_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNowPlaying'
type MockAPI_GetNowPlaying_Call struct {
	*mock.Call
}

// GetNowPlaying is a helper method to define mock.On call
//   - page int
func (_e *MockAPI_Expecter) GetNowPlaying(page interface{}) *MockAPI_GetNowPlaying_Call {
	return &MockAPI_GetNowPlaying_Call{Call: _e.mock.On("GetNowPlaying", page)}
}

func (_c *MockAPI_GetNowPlaying_Call) Run(run func(page int)) *MockAPI_GetNowPlaying_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockAPI_GetNowPlaying_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_GetNowPlaying_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetNowPlaying_Call) RunAndReturn(run func(int) ([]models.Movie, error)) *MockAPI_GetNowPlaying_Call {
	_c.Call.Return(run)
	return _c
}

// GetPopular provides a mock function with given fields: page
func (_m *MockAPI) GetPopular(page int) ([]models.Movie, error) {
	ret := _m.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for GetPopular")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Movie, error)); ok {
		return rf(page)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Movie); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetPopular_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPopular'
type MockAPI_GetPopular_Call struct {
	*mock.Call
}

// GetPopular is a helper method to define mock.On call
//   - page int
func (_e *MockAPI_Expecter) GetPopular(page interface{}) *MockAPI_GetPopular_Call {
	return &MockAPI_GetPopular_Call{Call: _e.mock.On("GetPopular", page)}
}

func (_c *MockAPI_GetPopular_Call) Run(run func(page int)) *MockAPI_GetPopular_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockAPI_GetPopular_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_GetPopular_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetPopular_Call) RunAndReturn(run func(int) ([]models.Movie, error)) *MockAPI_GetPopular_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviders provides a mock function with given fields: mediaType, id
func (_m *MockAPI) GetProviders(mediaType string, id int) (json.RawMessage, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviders")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (json.RawMessage, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) json.RawMessage); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviders'
type MockAPI_GetProviders_Call struct {
	*mock.Call
}

// GetProviders is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockAPI_Expecter) GetProviders(mediaType interface{}, id interface{}) *MockAPI_GetProviders_Call {
	return &MockAPI_GetProviders_Call{Call: _e.mock.On("GetProviders", mediaType, id)}
}

func (_c *MockAPI_GetProviders_Call) Run(run func(mediaType string, id int)) *MockAPI_GetProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockAPI_GetProviders_Call) Return(_a0 json.RawMessage, _a1 error) *MockAPI_GetProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetProviders_Call) RunAndReturn(run func(string, int) (json.RawMessage, error)) *MockAPI_GetProviders_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopRated provides a mock function with given fields: page
func (_m *MockAPI) GetTopRated(page int) ([]models.Movie, error) {
	ret := _m.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for GetTopRated")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Movie, error)); ok {
		return rf(page)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Movie); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetTopRated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopRated'
type MockAPI_GetTopRated_Call struct {
	*mock.Call
}

// GetTopRated is a helper method to define mock.On call
//   - page int
func (_e *MockAPI_Expecter) GetTopRated(page interface{}) *MockAPI_GetTopRated_Call {
	return &MockAPI_GetTopRated_Call{Call: _e.mock.On("GetTopRated", page)}
}

func (_c *MockAPI_GetTopRated_Call) Run(run func(page int)) *MockAPI_GetTopRated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockAPI_GetTopRated_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_GetTopRated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetTopRated_Call) RunAndReturn(run func(int) ([]models.Movie, error)) *MockAPI_GetTopRated_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrending provides a mock function with given fields: mediaType, timeWindow
func (_m *MockAPI) GetTrending(mediaType string, timeWindow string) ([]models.Movie, error) {
	ret := _m.Called(mediaType, timeWindow)

	if len(ret) == 0 {
		panic("no return value specified for GetTrending")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]models.Movie, error)); ok {
		return rf(mediaType, timeWindow)
	}
	if rf, ok := ret.Get(0).(func(string, string) []models.Movie); ok {
		r0 = rf(mediaType, timeWindow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(mediaType, timeWindow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetTrending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrending'
type MockAPI_GetTrending_Call struct {
	*mock.Call
}

// GetTrending is a helper method to define mock.On call
//   - mediaType string
//   - timeWindow string
func (_e *MockAPI_Expecter) GetTrending(mediaType interface{}, timeWindow interface{}) *MockAPI_GetTrending_Call {
	return &MockAPI_GetTrending_Call{Call: _e.mock.On("GetTrending", mediaType, timeWindow)}
}

func (_c *MockAPI_GetTrending_Call) Run(run func(mediaType string, timeWindow string)) *MockAPI_GetTrending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAPI_GetTrending_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_GetTrending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetTrending_Call) RunAndReturn(run func(string, string) ([]models.Movie, error)) *MockAPI_GetTrending_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpcoming provides a mock function with given fields: page
func (_m *MockAPI) GetUpcoming(page int) ([]models.Movie, error) {
	ret := _m.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for GetUpcoming")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Movie, error)); ok {
		return rf(page)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Movie); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetUpcoming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpcoming'
type MockAPI_GetUpcoming_Call struct {
	*mock.Call
}

// GetUpcoming is a helper method to define mock.On call
//   - page int
func (_e *MockAPI_Expecter) GetUpcoming(page interface{}) *MockAPI_GetUpcoming_Call {
	return &MockAPI_GetUpcoming_Call{Call: _e.mock.On("GetUpcoming", page)}
}

func (_c *MockAPI_GetUpcoming_Call) Run(run func(page int)) *MockAPI_GetUpcoming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockAPI_GetUpcoming_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_GetUpcoming_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetUpcoming_Call) RunAndReturn(run func(int) ([]models.Movie, error)) *MockAPI_GetUpcoming_Call {
	_c.Call.Return(run)
	return _c
}

// GetVideos provides a mock function with given fields: mediaType, id
func (_m *MockAPI) GetVideos(mediaType string, id int) ([]tmdb.Video, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVideos")
	}

	var r0 []tmdb.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]tmdb.Video, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) []tmdb.Video); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetVideos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVideos'
type MockAPI_GetVideos_Call struct {
	*mock.Call
}

// GetVideos is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockAPI_Expecter) GetVideos(mediaType interface{}, id interface{}) *MockAPI_GetVideos_Call {
	return &MockAPI_GetVideos_Call{Call: _e.mock.On("GetVideos", mediaType, id)}
}

func (_c *MockAPI_GetVideos_Call) Run(run func(mediaType string, id int)) *MockAPI_GetVideos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockAPI_GetVideos_Call) Return(_a0 []tmdb.Video, _a1 error) *MockAPI_GetVideos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetVideos_Call) RunAndReturn(run func(string, int) ([]tmdb.Video, error)) *MockAPI_GetVideos_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMovies provides a mock function with given fields: query, page
func (_m *MockAPI) SearchMovies(query string, page int) ([]models.Movie, error) {
	ret := _m.Called(query, page)

	if len(ret) == 0 {
		panic("no return value specified for SearchMovies")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]models.Movie, error)); ok {
		return rf(query, page)
	}
	if rf, ok := ret.Get(0).(func(string, int) []models.Movie); ok {
		r0 = rf(query, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(query, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_SearchMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMovies'
type MockAPI_SearchMovies_Call struct {
	*mock.Call
}

// SearchMovies is a helper method to define mock.On call
//   - query string
//   - page int
func (_e *MockAPI_Expecter) SearchMovies(query interface{}, page interface{}) *MockAPI_SearchMovies_Call {
	return &MockAPI_SearchMovies_Call{Call: _e.mock.On("SearchMovies", query, page)}
}

func (_c *MockAPI_SearchMovies_Call) Run(run func(query string, page int)) *MockAPI_SearchMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockAPI_SearchMovies_Call) Return(_a0 []models.Movie, _a1 error) *MockAPI_SearchMovies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_SearchMovies_Call) RunAndReturn(run func(string, int) ([]models.Movie, error)) *MockAPI_SearchMovies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
