// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	tmdb "github.com/milansax96/movie-terminal-api/pkg/tmdb"
	mock "github.com/stretchr/testify/mock"
)

// MockTMDBClient is an autogenerated mock type for the TMDBClient type
type MockTMDBClient struct {
	mock.Mock
}

type MockTMDBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTMDBClient) EXPECT() *MockTMDBClient_Expecter {
	return &MockTMDBClient_Expecter{mock: &_m.Mock}
}

// DiscoverByGenre provides a mock function with given fields: genreID, page
func (_m *MockTMDBClient) DiscoverByGenre(genreID int, page int) ([]tmdb.Movie, error) {
	ret := _m.Called(genreID, page)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverByGenre")
	}

	var r0 []tmdb.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]tmdb.Movie, error)); ok {
		return rf(genreID, page)
	}
	if rf, ok := ret.Get(0).(func(int, int) []tmdb.Movie); ok {
		r0 = rf(genreID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(genreID, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_DiscoverByGenre_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverByGenre'
type MockTMDBClient_DiscoverByGenre_Call struct {
	*mock.Call
}

// DiscoverByGenre is a helper method to define mock.On call
//   - genreID int
//   - page int
func (_e *MockTMDBClient_Expecter) DiscoverByGenre(genreID interface{}, page interface{}) *MockTMDBClient_DiscoverByGenre_Call {
	return &MockTMDBClient_DiscoverByGenre_Call{Call: _e.mock.On("DiscoverByGenre", genreID, page)}
}

func (_c *MockTMDBClient_DiscoverByGenre_Call) Run(run func(genreID int, page int)) *MockTMDBClient_DiscoverByGenre_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTMDBClient_DiscoverByGenre_Call) Return(_a0 []tmdb.Movie, _a1 error) *MockTMDBClient_DiscoverByGenre_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_DiscoverByGenre_Call) RunAndReturn(run func(int, int) ([]tmdb.Movie, error)) *MockTMDBClient_DiscoverByGenre_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredits provides a mock function with given fields: mediaType, id
func (_m *MockTMDBClient) GetCredits(mediaType string, id int) (*tmdb.CreditsResponse, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredits")
	}

	var r0 *tmdb.CreditsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*tmdb.CreditsResponse, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *tmdb.CreditsResponse); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.CreditsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_GetCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredits'
type MockTMDBClient_GetCredits_Call struct {
	*mock.Call
}

// GetCredits is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockTMDBClient_Expecter) GetCredits(mediaType interface{}, id interface{}) *MockTMDBClient_GetCredits_Call {
	return &MockTMDBClient_GetCredits_Call{Call: _e.mock.On("GetCredits", mediaType, id)}
}

func (_c *MockTMDBClient_GetCredits_Call) Run(run func(mediaType string, id int)) *MockTMDBClient_GetCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockTMDBClient_GetCredits_Call) Return(_a0 *tmdb.CreditsResponse, _a1 error) *MockTMDBClient_GetCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_GetCredits_Call) RunAndReturn(run func(string, int) (*tmdb.CreditsResponse, error)) *MockTMDBClient_GetCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieDetails provides a mock function with given fields: mediaType, id
func (_m *MockTMDBClient) GetMovieDetails(mediaType string, id int) (*tmdb.MovieDetail, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieDetails")
	}

	var r0 *tmdb.MovieDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*tmdb.MovieDetail, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *tmdb.MovieDetail); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.MovieDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_GetMovieDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieDetails'
type MockTMDBClient_GetMovieDetails_Call struct {
	*mock.Call
}

// GetMovieDetails is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockTMDBClient_Expecter) GetMovieDetails(mediaType interface{}, id interface{}) *MockTMDBClient_GetMovieDetails_Call {
	return &MockTMDBClient_GetMovieDetails_Call{Call: _e.mock.On("GetMovieDetails", mediaType, id)}
}

func (_c *MockTMDBClient_GetMovieDetails_Call) Run(run func(mediaType string, id int)) *MockTMDBClient_GetMovieDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockTMDBClient_GetMovieDetails_Call) Return(_a0 *tmdb.MovieDetail, _a1 error) *MockTMDBClient_GetMovieDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_GetMovieDetails_Call) RunAndReturn(run func(string, int) (*tmdb.MovieDetail, error)) *MockTMDBClient_GetMovieDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviders provides a mock function with given fields: mediaType, id
func (_m *MockTMDBClient) GetProviders(mediaType string, id int) (json.RawMessage, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviders")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (json.RawMessage, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) json.RawMessage); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_GetProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviders'
type MockTMDBClient_GetProviders_Call struct {
	*mock.Call
}

// GetProviders is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockTMDBClient_Expecter) GetProviders(mediaType interface{}, id interface{}) *MockTMDBClient_GetProviders_Call {
	return &MockTMDBClient_GetProviders_Call{Call: _e.mock.On("GetProviders", mediaType, id)}
}

func (_c *MockTMDBClient_GetProviders_Call) Run(run func(mediaType string, id int)) *MockTMDBClient_GetProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockTMDBClient_GetProviders_Call) Return(_a0 json.RawMessage, _a1 error) *MockTMDBClient_GetProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_GetProviders_Call) RunAndReturn(run func(string, int) (json.RawMessage, error)) *MockTMDBClient_GetProviders_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopRated provides a mock function with given fields: page
func (_m *MockTMDBClient) GetTopRated(page int) ([]tmdb.Movie, error) {
	ret := _m.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for GetTopRated")
	}

	var r0 []tmdb.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]tmdb.Movie, error)); ok {
		return rf(page)
	}
	if rf, ok := ret.Get(0).(func(int) []tmdb.Movie); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_GetTopRated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopRated'
type MockTMDBClient_GetTopRated_Call struct {
	*mock.Call
}

// GetTopRated is a helper method to define mock.On call
//   - page int
func (_e *MockTMDBClient_Expecter) GetTopRated(page interface{}) *MockTMDBClient_GetTopRated_Call {
	return &MockTMDBClient_GetTopRated_Call{Call: _e.mock.On("GetTopRated", page)}
}

func (_c *MockTMDBClient_GetTopRated_Call) Run(run func(page int)) *MockTMDBClient_GetTopRated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTMDBClient_GetTopRated_Call) Return(_a0 []tmdb.Movie, _a1 error) *MockTMDBClient_GetTopRated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_GetTopRated_Call) RunAndReturn(run func(int) ([]tmdb.Movie, error)) *MockTMDBClient_GetTopRated_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrending provides a mock function with given fields: mediaType, timeWindow
func (_m *MockTMDBClient) GetTrending(mediaType string, timeWindow string) ([]tmdb.Movie, error) {
	ret := _m.Called(mediaType, timeWindow)

	if len(ret) == 0 {
		panic("no return value specified for GetTrending")
	}

	var r0 []tmdb.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]tmdb.Movie, error)); ok {
		return rf(mediaType, timeWindow)
	}
	if rf, ok := ret.Get(0).(func(string, string) []tmdb.Movie); ok {
		r0 = rf(mediaType, timeWindow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(mediaType, timeWindow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_GetTrending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrending'
type MockTMDBClient_GetTrending_Call struct {
	*mock.Call
}

// GetTrending is a helper method to define mock.On call
//   - mediaType string
//   - timeWindow string
func (_e *MockTMDBClient_Expecter) GetTrending(mediaType interface{}, timeWindow interface{}) *MockTMDBClient_GetTrending_Call {
	return &MockTMDBClient_GetTrending_Call{Call: _e.mock.On("GetTrending", mediaType, timeWindow)}
}

func (_c *MockTMDBClient_GetTrending_Call) Run(run func(mediaType string, timeWindow string)) *MockTMDBClient_GetTrending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTMDBClient_GetTrending_Call) Return(_a0 []tmdb.Movie, _a1 error) *MockTMDBClient_GetTrending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_GetTrending_Call) RunAndReturn(run func(string, string) ([]tmdb.Movie, error)) *MockTMDBClient_GetTrending_Call {
	_c.Call.Return(run)
	return _c
}

// GetVideos provides a mock function with given fields: mediaType, id
func (_m *MockTMDBClient) GetVideos(mediaType string, id int) ([]tmdb.Video, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVideos")
	}

	var r0 []tmdb.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]tmdb.Video, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) []tmdb.Video); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_GetVideos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVideos'
type MockTMDBClient_GetVideos_Call struct {
	*mock.Call
}

// GetVideos is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockTMDBClient_Expecter) GetVideos(mediaType interface{}, id interface{}) *MockTMDBClient_GetVideos_Call {
	return &MockTMDBClient_GetVideos_Call{Call: _e.mock.On("GetVideos", mediaType, id)}
}

func (_c *MockTMDBClient_GetVideos_Call) Run(run func(mediaType string, id int)) *MockTMDBClient_GetVideos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockTMDBClient_GetVideos_Call) Return(_a0 []tmdb.Video, _a1 error) *MockTMDBClient_GetVideos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_GetVideos_Call) RunAndReturn(run func(string, int) ([]tmdb.Video, error)) *MockTMDBClient_GetVideos_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMovies provides a mock function with given fields: query, page
func (_m *MockTMDBClient) SearchMovies(query string, page int) ([]tmdb.Movie, error) {
	ret := _m.Called(query, page)

	if len(ret) == 0 {
		panic("no return value specified for SearchMovies")
	}

	var r0 []tmdb.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]tmdb.Movie, error)); ok {
		return rf(query, page)
	}
	if rf, ok := ret.Get(0).(func(string, int) []tmdb.Movie); ok {
		r0 = rf(query, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(query, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTMDBClient_SearchMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMovies'
type MockTMDBClient_SearchMovies_Call struct {
	*mock.Call
}

// SearchMovies is a helper method to define mock.On call
//   - query string
//   - page int
func (_e *MockTMDBClient_Expecter) SearchMovies(query interface{}, page interface{}) *MockTMDBClient_SearchMovies_Call {
	return &MockTMDBClient_SearchMovies_Call{Call: _e.mock.On("SearchMovies", query, page)}
}

func (_c *MockTMDBClient_SearchMovies_Call) Run(run func(query string, page int)) *MockTMDBClient_SearchMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockTMDBClient_SearchMovies_Call) Return(_a0 []tmdb.Movie, _a1 error) *MockTMDBClient_SearchMovies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTMDBClient_SearchMovies_Call) RunAndReturn(run func(string, int) ([]tmdb.Movie, error)) *MockTMDBClient_SearchMovies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTMDBClient creates a new instance of MockTMDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTMDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTMDBClient {
	mock := &MockTMDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
