with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  github.com/milansax96/movie-terminal-api/pkg/tmdb:
    interfaces:
      TMDBClient:
  github.com/milansax96/movie-terminal-api/internal/repository:
    interfaces:
      UserRepository:
      WatchlistRepository:
      FriendshipRepository:
      PostRepository:
  github.com/milansax96/movie-terminal-api/internal/service:
    interfaces:
      AuthServiceInterface:
      UserServiceInterface:
      MovieServiceInterface:
      SocialServiceInterface:
