// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFriendshipRepository is an autogenerated mock type for the FriendshipRepository type
type MockFriendshipRepository struct {
	mock.Mock
}

type MockFriendshipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendshipRepository) EXPECT() *MockFriendshipRepository_Expecter {
	return &MockFriendshipRepository_Expecter{mock: &_m.Mock}
}

// AcceptRequest provides a mock function with given fields: requestID, friendID
func (_m *MockFriendshipRepository) AcceptRequest(requestID uuid.UUID, friendID uuid.UUID) (*models.Friendship, error) {
	ret := _m.Called(requestID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptRequest")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.Friendship, error)); ok {
		return rf(requestID, friendID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.Friendship); ok {
		r0 = rf(requestID, friendID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(requestID, friendID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_AcceptRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptRequest'
type MockFriendshipRepository_AcceptRequest_Call struct {
	*mock.Call
}

// AcceptRequest is a helper method to define mock.On call
//   - requestID uuid.UUID
//   - friendID uuid.UUID
func (_e *MockFriendshipRepository_Expecter) AcceptRequest(requestID interface{}, friendID interface{}) *MockFriendshipRepository_AcceptRequest_Call {
	return &MockFriendshipRepository_AcceptRequest_Call{Call: _e.mock.On("AcceptRequest", requestID, friendID)}
}

func (_c *MockFriendshipRepository_AcceptRequest_Call) Run(run func(requestID uuid.UUID, friendID uuid.UUID)) *MockFriendshipRepository_AcceptRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFriendshipRepository_AcceptRequest_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipRepository_AcceptRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_AcceptRequest_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*models.Friendship, error)) *MockFriendshipRepository_AcceptRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: friendship
func (_m *MockFriendshipRepository) Create(friendship *models.Friendship) error {
	ret := _m.Called(friendship)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Friendship) error); ok {
		r0 = rf(friendship)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFriendshipRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFriendshipRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - friendship *models.Friendship
func (_e *MockFriendshipRepository_Expecter) Create(friendship interface{}) *MockFriendshipRepository_Create_Call {
	return &MockFriendshipRepository_Create_Call{Call: _e.mock.On("Create", friendship)}
}

func (_c *MockFriendshipRepository_Create_Call) Run(run func(friendship *models.Friendship)) *MockFriendshipRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Friendship))
	})
	return _c
}

func (_c *MockFriendshipRepository_Create_Call) Return(_a0 error) *MockFriendshipRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFriendshipRepository_Create_Call) RunAndReturn(run func(*models.Friendship) error) *MockFriendshipRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAcceptedFriendships provides a mock function with given fields: userID
func (_m *MockFriendshipRepository) GetAcceptedFriendships(userID uuid.UUID) ([]models.Friendship, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAcceptedFriendships")
	}

	var r0 []models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Friendship, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Friendship); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_GetAcceptedFriendships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAcceptedFriendships'
type MockFriendshipRepository_GetAcceptedFriendships_Call struct {
	*mock.Call
}

// GetAcceptedFriendships is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockFriendshipRepository_Expecter) GetAcceptedFriendships(userID interface{}) *MockFriendshipRepository_GetAcceptedFriendships_Call {
	return &MockFriendshipRepository_GetAcceptedFriendships_Call{Call: _e.mock.On("GetAcceptedFriendships", userID)}
}

func (_c *MockFriendshipRepository_GetAcceptedFriendships_Call) Run(run func(userID uuid.UUID)) *MockFriendshipRepository_GetAcceptedFriendships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockFriendshipRepository_GetAcceptedFriendships_Call) Return(_a0 []models.Friendship, _a1 error) *MockFriendshipRepository_GetAcceptedFriendships_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_GetAcceptedFriendships_Call) RunAndReturn(run func(uuid.UUID) ([]models.Friendship, error)) *MockFriendshipRepository_GetAcceptedFriendships_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFriendshipRepository creates a new instance of MockFriendshipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendshipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
