// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: user
func (_m *MockUserRepository) Create(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepository_Expecter) Create(user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(user *models.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(*models.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGoogleID provides a mock function with given fields: googleID
func (_m *MockUserRepository) FindByGoogleID(googleID string) (*models.User, error) {
	ret := _m.Called(googleID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGoogleID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(googleID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(googleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(googleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGoogleID'
type MockUserRepository_FindByGoogleID_Call struct {
	*mock.Call
}

// FindByGoogleID is a helper method to define mock.On call
//   - googleID string
func (_e *MockUserRepository_Expecter) FindByGoogleID(googleID interface{}) *MockUserRepository_FindByGoogleID_Call {
	return &MockUserRepository_FindByGoogleID_Call{Call: _e.mock.On("FindByGoogleID", googleID)}
}

func (_c *MockUserRepository_FindByGoogleID_Call) Run(run func(googleID string)) *MockUserRepository_FindByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByGoogleID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindByGoogleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByGoogleID_Call) RunAndReturn(run func(string) (*models.User, error)) *MockUserRepository_FindByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: userID
func (_m *MockUserRepository) FindByID(userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) FindByID(userID interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", userID)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(userID uuid.UUID)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithStreaming provides a mock function with given fields: userID
func (_m *MockUserRepository) FindByIDWithStreaming(userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithStreaming")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByIDWithStreaming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithStreaming'
type MockUserRepository_FindByIDWithStreaming_Call struct {
	*mock.Call
}

// FindByIDWithStreaming is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) FindByIDWithStreaming(userID interface{}) *MockUserRepository_FindByIDWithStreaming_Call {
	return &MockUserRepository_FindByIDWithStreaming_Call{Call: _e.mock.On("FindByIDWithStreaming", userID)}
}

func (_c *MockUserRepository_FindByIDWithStreaming_Call) Run(run func(userID uuid.UUID)) *MockUserRepository_FindByIDWithStreaming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_FindByIDWithStreaming_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindByIDWithStreaming_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByIDWithStreaming_Call) RunAndReturn(run func(uuid.UUID) (*models.User, error)) *MockUserRepository_FindByIDWithStreaming_Call {
	_c.Call.Return(run)
	return _c
}

// FindStreamingServicesByIDs provides a mock function with given fields: ids
func (_m *MockUserRepository) FindStreamingServicesByIDs(ids []int) ([]models.StreamingService, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for FindStreamingServicesByIDs")
	}

	var r0 []models.StreamingService
	var r1 error
	if rf, ok := ret.Get(0).(func([]int) ([]models.StreamingService, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]int) []models.StreamingService); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.StreamingService)
		}
	}

	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindStreamingServicesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindStreamingServicesByIDs'
type MockUserRepository_FindStreamingServicesByIDs_Call struct {
	*mock.Call
}

// FindStreamingServicesByIDs is a helper method to define mock.On call
//   - ids []int
func (_e *MockUserRepository_Expecter) FindStreamingServicesByIDs(ids interface{}) *MockUserRepository_FindStreamingServicesByIDs_Call {
	return &MockUserRepository_FindStreamingServicesByIDs_Call{Call: _e.mock.On("FindStreamingServicesByIDs", ids)}
}

func (_c *MockUserRepository_FindStreamingServicesByIDs_Call) Run(run func(ids []int)) *MockUserRepository_FindStreamingServicesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockUserRepository_FindStreamingServicesByIDs_Call) Return(_a0 []models.StreamingService, _a1 error) *MockUserRepository_FindStreamingServicesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindStreamingServicesByIDs_Call) RunAndReturn(run func([]int) ([]models.StreamingService, error)) *MockUserRepository_FindStreamingServicesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceStreamingServices provides a mock function with given fields: userID, services
func (_m *MockUserRepository) ReplaceStreamingServices(userID uuid.UUID, services []models.StreamingService) error {
	ret := _m.Called(userID, services)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceStreamingServices")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []models.StreamingService) error); ok {
		r0 = rf(userID, services)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_ReplaceStreamingServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceStreamingServices'
type MockUserRepository_ReplaceStreamingServices_Call struct {
	*mock.Call
}

// ReplaceStreamingServices is a helper method to define mock.On call
//   - userID uuid.UUID
//   - services []models.StreamingService
func (_e *MockUserRepository_Expecter) ReplaceStreamingServices(userID interface{}, services interface{}) *MockUserRepository_ReplaceStreamingServices_Call {
	return &MockUserRepository_ReplaceStreamingServices_Call{Call: _e.mock.On("ReplaceStreamingServices", userID, services)}
}

func (_c *MockUserRepository_ReplaceStreamingServices_Call) Run(run func(userID uuid.UUID, services []models.StreamingService)) *MockUserRepository_ReplaceStreamingServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].([]models.StreamingService))
	})
	return _c
}

func (_c *MockUserRepository_ReplaceStreamingServices_Call) Return(_a0 error) *MockUserRepository_ReplaceStreamingServices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_ReplaceStreamingServices_Call) RunAndReturn(run func(uuid.UUID, []models.StreamingService) error) *MockUserRepository_ReplaceStreamingServices_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByUsername provides a mock function with given fields: query, limit
func (_m *MockUserRepository) SearchByUsername(query string, limit int) ([]models.User, error) {
	ret := _m.Called(query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByUsername")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]models.User, error)); ok {
		return rf(query, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []models.User); ok {
		r0 = rf(query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_SearchByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByUsername'
type MockUserRepository_SearchByUsername_Call struct {
	*mock.Call
}

// SearchByUsername is a helper method to define mock.On call
//   - query string
//   - limit int
func (_e *MockUserRepository_Expecter) SearchByUsername(query interface{}, limit interface{}) *MockUserRepository_SearchByUsername_Call {
	return &MockUserRepository_SearchByUsername_Call{Call: _e.mock.On("SearchByUsername", query, limit)}
}

func (_c *MockUserRepository_SearchByUsername_Call) Run(run func(query string, limit int)) *MockUserRepository_SearchByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepository_SearchByUsername_Call) Return(_a0 []models.User, _a1 error) *MockUserRepository_SearchByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_SearchByUsername_Call) RunAndReturn(run func(string, int) ([]models.User, error)) *MockUserRepository_SearchByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfilePicture provides a mock function with given fields: userID, picture
func (_m *MockUserRepository) UpdateProfilePicture(userID uuid.UUID, picture string) error {
	ret := _m.Called(userID, picture)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfilePicture")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(userID, picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfilePicture'
type MockUserRepository_UpdateProfilePicture_Call struct {
	*mock.Call
}

// UpdateProfilePicture is a helper method to define mock.On call
//   - userID uuid.UUID
//   - picture string
func (_e *MockUserRepository_Expecter) UpdateProfilePicture(userID interface{}, picture interface{}) *MockUserRepository_UpdateProfilePicture_Call {
	return &MockUserRepository_UpdateProfilePicture_Call{Call: _e.mock.On("UpdateProfilePicture", userID, picture)}
}

func (_c *MockUserRepository_UpdateProfilePicture_Call) Run(run func(userID uuid.UUID, picture string)) *MockUserRepository_UpdateProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_UpdateProfilePicture_Call) Return(_a0 error) *MockUserRepository_UpdateProfilePicture_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateProfilePicture_Call) RunAndReturn(run func(uuid.UUID, string) error) *MockUserRepository_UpdateProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
