// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWatchlistRepository is an autogenerated mock type for the WatchlistRepository type
type MockWatchlistRepository struct {
	mock.Mock
}

type MockWatchlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchlistRepository) EXPECT() *MockWatchlistRepository_Expecter {
	return &MockWatchlistRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: item
func (_m *MockWatchlistRepository) Add(item *models.Watchlist) error {
	ret := _m.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Watchlist) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWatchlistRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockWatchlistRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - item *models.Watchlist
func (_e *MockWatchlistRepository_Expecter) Add(item interface{}) *MockWatchlistRepository_Add_Call {
	return &MockWatchlistRepository_Add_Call{Call: _e.mock.On("Add", item)}
}

func (_c *MockWatchlistRepository_Add_Call) Run(run func(item *models.Watchlist)) *MockWatchlistRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Watchlist))
	})
	return _c
}

func (_c *MockWatchlistRepository_Add_Call) Return(_a0 error) *MockWatchlistRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWatchlistRepository_Add_Call) RunAndReturn(run func(*models.Watchlist) error) *MockWatchlistRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: userID, tmdbID
func (_m *MockWatchlistRepository) Exists(userID uuid.UUID, tmdbID int) (bool, error) {
	ret := _m.Called(userID, tmdbID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) (bool, error)); ok {
		return rf(userID, tmdbID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) bool); ok {
		r0 = rf(userID, tmdbID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int) error); ok {
		r1 = rf(userID, tmdbID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchlistRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockWatchlistRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - userID uuid.UUID
//   - tmdbID int
func (_e *MockWatchlistRepository_Expecter) Exists(userID interface{}, tmdbID interface{}) *MockWatchlistRepository_Exists_Call {
	return &MockWatchlistRepository_Exists_Call{Call: _e.mock.On("Exists", userID, tmdbID)}
}

func (_c *MockWatchlistRepository_Exists_Call) Run(run func(userID uuid.UUID, tmdbID int)) *MockWatchlistRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockWatchlistRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockWatchlistRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchlistRepository_Exists_Call) RunAndReturn(run func(uuid.UUID, int) (bool, error)) *MockWatchlistRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: userID
func (_m *MockWatchlistRepository) GetByUserID(userID uuid.UUID) ([]models.Watchlist, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []models.Watchlist
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Watchlist, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Watchlist); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Watchlist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchlistRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockWatchlistRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockWatchlistRepository_Expecter) GetByUserID(userID interface{}) *MockWatchlistRepository_GetByUserID_Call {
	return &MockWatchlistRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", userID)}
}

func (_c *MockWatchlistRepository_GetByUserID_Call) Run(run func(userID uuid.UUID)) *MockWatchlistRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockWatchlistRepository_GetByUserID_Call) Return(_a0 []models.Watchlist, _a1 error) *MockWatchlistRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchlistRepository_GetByUserID_Call) RunAndReturn(run func(uuid.UUID) ([]models.Watchlist, error)) *MockWatchlistRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: userID, tmdbID
func (_m *MockWatchlistRepository) Remove(userID uuid.UUID, tmdbID int) (int64, error) {
	ret := _m.Called(userID, tmdbID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) (int64, error)); ok {
		return rf(userID, tmdbID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) int64); ok {
		r0 = rf(userID, tmdbID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int) error); ok {
		r1 = rf(userID, tmdbID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchlistRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockWatchlistRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - userID uuid.UUID
//   - tmdbID int
func (_e *MockWatchlistRepository_Expecter) Remove(userID interface{}, tmdbID interface{}) *MockWatchlistRepository_Remove_Call {
	return &MockWatchlistRepository_Remove_Call{Call: _e.mock.On("Remove", userID, tmdbID)}
}

func (_c *MockWatchlistRepository_Remove_Call) Run(run func(userID uuid.UUID, tmdbID int)) *MockWatchlistRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockWatchlistRepository_Remove_Call) Return(_a0 int64, _a1 error) *MockWatchlistRepository_Remove_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchlistRepository_Remove_Call) RunAndReturn(run func(uuid.UUID, int) (int64, error)) *MockWatchlistRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWatchlistRepository creates a new instance of MockWatchlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchlistRepository {
	mock := &MockWatchlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
