// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPostRepository is an autogenerated mock type for the PostRepository type
type MockPostRepository struct {
	mock.Mock
}

type MockPostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepository) EXPECT() *MockPostRepository_Expecter {
	return &MockPostRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: post
func (_m *MockPostRepository) Create(post *models.Post) error {
	ret := _m.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Post) error); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - post *models.Post
func (_e *MockPostRepository_Expecter) Create(post interface{}) *MockPostRepository_Create_Call {
	return &MockPostRepository_Create_Call{Call: _e.mock.On("Create", post)}
}

func (_c *MockPostRepository_Create_Call) Run(run func(post *models.Post)) *MockPostRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Post))
	})
	return _c
}

func (_c *MockPostRepository_Create_Call) Return(_a0 error) *MockPostRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostRepository_Create_Call) RunAndReturn(run func(*models.Post) error) *MockPostRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDs provides a mock function with given fields: userIDs, limit
func (_m *MockPostRepository) GetByUserIDs(userIDs []uuid.UUID, limit int) ([]models.Post, error) {
	ret := _m.Called(userIDs, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDs")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func([]uuid.UUID, int) ([]models.Post, error)); ok {
		return rf(userIDs, limit)
	}
	if rf, ok := ret.Get(0).(func([]uuid.UUID, int) []models.Post); ok {
		r0 = rf(userIDs, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func([]uuid.UUID, int) error); ok {
		r1 = rf(userIDs, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepository_GetByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDs'
type MockPostRepository_GetByUserIDs_Call struct {
	*mock.Call
}

// GetByUserIDs is a helper method to define mock.On call
//   - userIDs []uuid.UUID
//   - limit int
func (_e *MockPostRepository_Expecter) GetByUserIDs(userIDs interface{}, limit interface{}) *MockPostRepository_GetByUserIDs_Call {
	return &MockPostRepository_GetByUserIDs_Call{Call: _e.mock.On("GetByUserIDs", userIDs, limit)}
}

func (_c *MockPostRepository_GetByUserIDs_Call) Run(run func(userIDs []uuid.UUID, limit int)) *MockPostRepository_GetByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockPostRepository_GetByUserIDs_Call) Return(_a0 []models.Post, _a1 error) *MockPostRepository_GetByUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepository_GetByUserIDs_Call) RunAndReturn(run func([]uuid.UUID, int) ([]models.Post, error)) *MockPostRepository_GetByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostRepository creates a new instance of MockPostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepository {
	mock := &MockPostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
