// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function with given fields: userID
func (_m *MockUserServiceInterface) GetProfile(userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockUserServiceInterface_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockUserServiceInterface_Expecter) GetProfile(userID interface{}) *MockUserServiceInterface_GetProfile_Call {
	return &MockUserServiceInterface_GetProfile_Call{Call: _e.mock.On("GetProfile", userID)}
}

func (_c *MockUserServiceInterface_GetProfile_Call) Run(run func(userID uuid.UUID)) *MockUserServiceInterface_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServiceInterface_GetProfile_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInterface_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_GetProfile_Call) RunAndReturn(run func(uuid.UUID) (*models.User, error)) *MockUserServiceInterface_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamingServices provides a mock function with given fields: userID, serviceIDs
func (_m *MockUserServiceInterface) UpdateStreamingServices(userID uuid.UUID, serviceIDs []int) error {
	ret := _m.Called(userID, serviceIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamingServices")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []int) error); ok {
		r0 = rf(userID, serviceIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceInterface_UpdateStreamingServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamingServices'
type MockUserServiceInterface_UpdateStreamingServices_Call struct {
	*mock.Call
}

// UpdateStreamingServices is a helper method to define mock.On call
//   - userID uuid.UUID
//   - serviceIDs []int
func (_e *MockUserServiceInterface_Expecter) UpdateStreamingServices(userID interface{}, serviceIDs interface{}) *MockUserServiceInterface_UpdateStreamingServices_Call {
	return &MockUserServiceInterface_UpdateStreamingServices_Call{Call: _e.mock.On("UpdateStreamingServices", userID, serviceIDs)}
}

func (_c *MockUserServiceInterface_UpdateStreamingServices_Call) Run(run func(userID uuid.UUID, serviceIDs []int)) *MockUserServiceInterface_UpdateStreamingServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].([]int))
	})
	return _c
}

func (_c *MockUserServiceInterface_UpdateStreamingServices_Call) Return(_a0 error) *MockUserServiceInterface_UpdateStreamingServices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceInterface_UpdateStreamingServices_Call) RunAndReturn(run func(uuid.UUID, []int) error) *MockUserServiceInterface_UpdateStreamingServices_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
