// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/milansax96/movie-terminal-api/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// GoogleLogin provides a mock function with given fields: ctx, idToken
func (_m *MockAuthServiceInterface) GoogleLogin(ctx context.Context, idToken string) (*service.AuthResult, error) {
	ret := _m.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for GoogleLogin")
	}

	var r0 *service.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.AuthResult, error)); ok {
		return rf(ctx, idToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.AuthResult); ok {
		r0 = rf(ctx, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_GoogleLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GoogleLogin'
type MockAuthServiceInterface_GoogleLogin_Call struct {
	*mock.Call
}

// GoogleLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
func (_e *MockAuthServiceInterface_Expecter) GoogleLogin(ctx interface{}, idToken interface{}) *MockAuthServiceInterface_GoogleLogin_Call {
	return &MockAuthServiceInterface_GoogleLogin_Call{Call: _e.mock.On("GoogleLogin", ctx, idToken)}
}

func (_c *MockAuthServiceInterface_GoogleLogin_Call) Run(run func(ctx context.Context, idToken string)) *MockAuthServiceInterface_GoogleLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_GoogleLogin_Call) Return(_a0 *service.AuthResult, _a1 error) *MockAuthServiceInterface_GoogleLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_GoogleLogin_Call) RunAndReturn(run func(context.Context, string) (*service.AuthResult, error)) *MockAuthServiceInterface_GoogleLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
