// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
	tmdb "github.com/milansax96/movie-terminal-api/pkg/tmdb"
)

// MockMovieServiceInterface is an autogenerated mock type for the MovieServiceInterface type
type MockMovieServiceInterface struct {
	mock.Mock
}

type MockMovieServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMovieServiceInterface) EXPECT() *MockMovieServiceInterface_Expecter {
	return &MockMovieServiceInterface_Expecter{mock: &_m.Mock}
}

// AddToWatchlist provides a mock function with given fields: userID, movie
func (_m *MockMovieServiceInterface) AddToWatchlist(userID uuid.UUID, movie models.Movie) (*models.Watchlist, error) {
	ret := _m.Called(userID, movie)

	if len(ret) == 0 {
		panic("no return value specified for AddToWatchlist")
	}

	var r0 *models.Watchlist
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, models.Movie) (*models.Watchlist, error)); ok {
		return rf(userID, movie)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, models.Movie) *models.Watchlist); ok {
		r0 = rf(userID, movie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Watchlist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, models.Movie) error); ok {
		r1 = rf(userID, movie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_AddToWatchlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToWatchlist'
type MockMovieServiceInterface_AddToWatchlist_Call struct {
	*mock.Call
}

// AddToWatchlist is a helper method to define mock.On call
//   - userID uuid.UUID
//   - movie models.Movie
func (_e *MockMovieServiceInterface_Expecter) AddToWatchlist(userID interface{}, movie interface{}) *MockMovieServiceInterface_AddToWatchlist_Call {
	return &MockMovieServiceInterface_AddToWatchlist_Call{Call: _e.mock.On("AddToWatchlist", userID, movie)}
}

func (_c *MockMovieServiceInterface_AddToWatchlist_Call) Run(run func(userID uuid.UUID, movie models.Movie)) *MockMovieServiceInterface_AddToWatchlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(models.Movie))
	})
	return _c
}

func (_c *MockMovieServiceInterface_AddToWatchlist_Call) Return(_a0 *models.Watchlist, _a1 error) *MockMovieServiceInterface_AddToWatchlist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_AddToWatchlist_Call) RunAndReturn(run func(uuid.UUID, models.Movie) (*models.Watchlist, error)) *MockMovieServiceInterface_AddToWatchlist_Call {
	_c.Call.Return(run)
	return _c
}

// CheckWatchlist provides a mock function with given fields: userID, movieID
func (_m *MockMovieServiceInterface) CheckWatchlist(userID uuid.UUID, movieID int) (bool, error) {
	ret := _m.Called(userID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for CheckWatchlist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) (bool, error)); ok {
		return rf(userID, movieID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) bool); ok {
		r0 = rf(userID, movieID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int) error); ok {
		r1 = rf(userID, movieID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_CheckWatchlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckWatchlist'
type MockMovieServiceInterface_CheckWatchlist_Call struct {
	*mock.Call
}

// CheckWatchlist is a helper method to define mock.On call
//   - userID uuid.UUID
//   - movieID int
func (_e *MockMovieServiceInterface_Expecter) CheckWatchlist(userID interface{}, movieID interface{}) *MockMovieServiceInterface_CheckWatchlist_Call {
	return &MockMovieServiceInterface_CheckWatchlist_Call{Call: _e.mock.On("CheckWatchlist", userID, movieID)}
}

func (_c *MockMovieServiceInterface_CheckWatchlist_Call) Run(run func(userID uuid.UUID, movieID int)) *MockMovieServiceInterface_CheckWatchlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_CheckWatchlist_Call) Return(_a0 bool, _a1 error) *MockMovieServiceInterface_CheckWatchlist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_CheckWatchlist_Call) RunAndReturn(run func(uuid.UUID, int) (bool, error)) *MockMovieServiceInterface_CheckWatchlist_Call {
	_c.Call.Return(run)
	return _c
}

// Discover provides a mock function with given fields: userID, genre, page
func (_m *MockMovieServiceInterface) Discover(userID uuid.UUID, genre string, page int) ([]models.Movie, error) {
	ret := _m.Called(userID, genre, page)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int) ([]models.Movie, error)); ok {
		return rf(userID, genre, page)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int) []models.Movie); ok {
		r0 = rf(userID, genre, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, int) error); ok {
		r1 = rf(userID, genre, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type MockMovieServiceInterface_Discover_Call struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - userID uuid.UUID
//   - genre string
//   - page int
func (_e *MockMovieServiceInterface_Expecter) Discover(userID interface{}, genre interface{}, page interface{}) *MockMovieServiceInterface_Discover_Call {
	return &MockMovieServiceInterface_Discover_Call{Call: _e.mock.On("Discover", userID, genre, page)}
}

func (_c *MockMovieServiceInterface_Discover_Call) Run(run func(userID uuid.UUID, genre string, page int)) *MockMovieServiceInterface_Discover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_Discover_Call) Return(_a0 []models.Movie, _a1 error) *MockMovieServiceInterface_Discover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_Discover_Call) RunAndReturn(run func(uuid.UUID, string, int) ([]models.Movie, error)) *MockMovieServiceInterface_Discover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredits provides a mock function with given fields: mediaType, id
func (_m *MockMovieServiceInterface) GetCredits(mediaType string, id int) (*tmdb.CreditsResponse, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredits")
	}

	var r0 *tmdb.CreditsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*tmdb.CreditsResponse, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *tmdb.CreditsResponse); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.CreditsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_GetCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredits'
type MockMovieServiceInterface_GetCredits_Call struct {
	*mock.Call
}

// GetCredits is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockMovieServiceInterface_Expecter) GetCredits(mediaType interface{}, id interface{}) *MockMovieServiceInterface_GetCredits_Call {
	return &MockMovieServiceInterface_GetCredits_Call{Call: _e.mock.On("GetCredits", mediaType, id)}
}

func (_c *MockMovieServiceInterface_GetCredits_Call) Run(run func(mediaType string, id int)) *MockMovieServiceInterface_GetCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_GetCredits_Call) Return(_a0 *tmdb.CreditsResponse, _a1 error) *MockMovieServiceInterface_GetCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_GetCredits_Call) RunAndReturn(run func(string, int) (*tmdb.CreditsResponse, error)) *MockMovieServiceInterface_GetCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetail provides a mock function with given fields: mediaType, id
func (_m *MockMovieServiceInterface) GetDetail(mediaType string, id int) (*tmdb.MovieDetail, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 *tmdb.MovieDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*tmdb.MovieDetail, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *tmdb.MovieDetail); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.MovieDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_GetDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetail'
type MockMovieServiceInterface_GetDetail_Call struct {
	*mock.Call
}

// GetDetail is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockMovieServiceInterface_Expecter) GetDetail(mediaType interface{}, id interface{}) *MockMovieServiceInterface_GetDetail_Call {
	return &MockMovieServiceInterface_GetDetail_Call{Call: _e.mock.On("GetDetail", mediaType, id)}
}

func (_c *MockMovieServiceInterface_GetDetail_Call) Run(run func(mediaType string, id int)) *MockMovieServiceInterface_GetDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_GetDetail_Call) Return(_a0 *tmdb.MovieDetail, _a1 error) *MockMovieServiceInterface_GetDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_GetDetail_Call) RunAndReturn(run func(string, int) (*tmdb.MovieDetail, error)) *MockMovieServiceInterface_GetDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviders provides a mock function with given fields: mediaType, id
func (_m *MockMovieServiceInterface) GetProviders(mediaType string, id int) (json.RawMessage, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviders")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (json.RawMessage, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) json.RawMessage); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_GetProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviders'
type MockMovieServiceInterface_GetProviders_Call struct {
	*mock.Call
}

// GetProviders is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockMovieServiceInterface_Expecter) GetProviders(mediaType interface{}, id interface{}) *MockMovieServiceInterface_GetProviders_Call {
	return &MockMovieServiceInterface_GetProviders_Call{Call: _e.mock.On("GetProviders", mediaType, id)}
}

func (_c *MockMovieServiceInterface_GetProviders_Call) Run(run func(mediaType string, id int)) *MockMovieServiceInterface_GetProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_GetProviders_Call) Return(_a0 json.RawMessage, _a1 error) *MockMovieServiceInterface_GetProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_GetProviders_Call) RunAndReturn(run func(string, int) (json.RawMessage, error)) *MockMovieServiceInterface_GetProviders_Call {
	_c.Call.Return(run)
	return _c
}

// GetVideos provides a mock function with given fields: mediaType, id
func (_m *MockMovieServiceInterface) GetVideos(mediaType string, id int) ([]tmdb.Video, error) {
	ret := _m.Called(mediaType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVideos")
	}

	var r0 []tmdb.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]tmdb.Video, error)); ok {
		return rf(mediaType, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) []tmdb.Video); ok {
		r0 = rf(mediaType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(mediaType, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_GetVideos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVideos'
type MockMovieServiceInterface_GetVideos_Call struct {
	*mock.Call
}

// GetVideos is a helper method to define mock.On call
//   - mediaType string
//   - id int
func (_e *MockMovieServiceInterface_Expecter) GetVideos(mediaType interface{}, id interface{}) *MockMovieServiceInterface_GetVideos_Call {
	return &MockMovieServiceInterface_GetVideos_Call{Call: _e.mock.On("GetVideos", mediaType, id)}
}

func (_c *MockMovieServiceInterface_GetVideos_Call) Run(run func(mediaType string, id int)) *MockMovieServiceInterface_GetVideos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_GetVideos_Call) Return(_a0 []tmdb.Video, _a1 error) *MockMovieServiceInterface_GetVideos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_GetVideos_Call) RunAndReturn(run func(string, int) ([]tmdb.Video, error)) *MockMovieServiceInterface_GetVideos_Call {
	_c.Call.Return(run)
	return _c
}

// GetWatchlist provides a mock function with given fields: userID
func (_m *MockMovieServiceInterface) GetWatchlist(userID uuid.UUID) ([]models.Watchlist, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWatchlist")
	}

	var r0 []models.Watchlist
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Watchlist, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Watchlist); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Watchlist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_GetWatchlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWatchlist'
type MockMovieServiceInterface_GetWatchlist_Call struct {
	*mock.Call
}

// GetWatchlist is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockMovieServiceInterface_Expecter) GetWatchlist(userID interface{}) *MockMovieServiceInterface_GetWatchlist_Call {
	return &MockMovieServiceInterface_GetWatchlist_Call{Call: _e.mock.On("GetWatchlist", userID)}
}

func (_c *MockMovieServiceInterface_GetWatchlist_Call) Run(run func(userID uuid.UUID)) *MockMovieServiceInterface_GetWatchlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMovieServiceInterface_GetWatchlist_Call) Return(_a0 []models.Watchlist, _a1 error) *MockMovieServiceInterface_GetWatchlist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_GetWatchlist_Call) RunAndReturn(run func(uuid.UUID) ([]models.Watchlist, error)) *MockMovieServiceInterface_GetWatchlist_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromWatchlist provides a mock function with given fields: userID, movieID
func (_m *MockMovieServiceInterface) RemoveFromWatchlist(userID uuid.UUID, movieID int) error {
	ret := _m.Called(userID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromWatchlist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) error); ok {
		r0 = rf(userID, movieID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMovieServiceInterface_RemoveFromWatchlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromWatchlist'
type MockMovieServiceInterface_RemoveFromWatchlist_Call struct {
	*mock.Call
}

// RemoveFromWatchlist is a helper method to define mock.On call
//   - userID uuid.UUID
//   - movieID int
func (_e *MockMovieServiceInterface_Expecter) RemoveFromWatchlist(userID interface{}, movieID interface{}) *MockMovieServiceInterface_RemoveFromWatchlist_Call {
	return &MockMovieServiceInterface_RemoveFromWatchlist_Call{Call: _e.mock.On("RemoveFromWatchlist", userID, movieID)}
}

func (_c *MockMovieServiceInterface_RemoveFromWatchlist_Call) Run(run func(userID uuid.UUID, movieID int)) *MockMovieServiceInterface_RemoveFromWatchlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_RemoveFromWatchlist_Call) Return(_a0 error) *MockMovieServiceInterface_RemoveFromWatchlist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMovieServiceInterface_RemoveFromWatchlist_Call) RunAndReturn(run func(uuid.UUID, int) error) *MockMovieServiceInterface_RemoveFromWatchlist_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: userID, query, page
func (_m *MockMovieServiceInterface) Search(userID uuid.UUID, query string, page int) ([]models.Movie, error) {
	ret := _m.Called(userID, query, page)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int) ([]models.Movie, error)); ok {
		return rf(userID, query, page)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int) []models.Movie); ok {
		r0 = rf(userID, query, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, int) error); ok {
		r1 = rf(userID, query, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieServiceInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMovieServiceInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - userID uuid.UUID
//   - query string
//   - page int
func (_e *MockMovieServiceInterface_Expecter) Search(userID interface{}, query interface{}, page interface{}) *MockMovieServiceInterface_Search_Call {
	return &MockMovieServiceInterface_Search_Call{Call: _e.mock.On("Search", userID, query, page)}
}

func (_c *MockMovieServiceInterface_Search_Call) Run(run func(userID uuid.UUID, query string, page int)) *MockMovieServiceInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockMovieServiceInterface_Search_Call) Return(_a0 []models.Movie, _a1 error) *MockMovieServiceInterface_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieServiceInterface_Search_Call) RunAndReturn(run func(uuid.UUID, string, int) ([]models.Movie, error)) *MockMovieServiceInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMovieServiceInterface creates a new instance of MockMovieServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMovieServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMovieServiceInterface {
	mock := &MockMovieServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
