// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/milansax96/movie-terminal-api/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSocialServiceInterface is an autogenerated mock type for the SocialServiceInterface type
type MockSocialServiceInterface struct {
	mock.Mock
}

type MockSocialServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSocialServiceInterface) EXPECT() *MockSocialServiceInterface_Expecter {
	return &MockSocialServiceInterface_Expecter{mock: &_m.Mock}
}

// AcceptFriendRequest provides a mock function with given fields: requestID, friendID
func (_m *MockSocialServiceInterface) AcceptFriendRequest(requestID uuid.UUID, friendID uuid.UUID) (*models.Friendship, error) {
	ret := _m.Called(requestID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptFriendRequest")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.Friendship, error)); ok {
		return rf(requestID, friendID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.Friendship); ok {
		r0 = rf(requestID, friendID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(requestID, friendID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialServiceInterface_AcceptFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptFriendRequest'
type MockSocialServiceInterface_AcceptFriendRequest_Call struct {
	*mock.Call
}

// AcceptFriendRequest is a helper method to define mock.On call
//   - requestID uuid.UUID
//   - friendID uuid.UUID
func (_e *MockSocialServiceInterface_Expecter) AcceptFriendRequest(requestID interface{}, friendID interface{}) *MockSocialServiceInterface_AcceptFriendRequest_Call {
	return &MockSocialServiceInterface_AcceptFriendRequest_Call{Call: _e.mock.On("AcceptFriendRequest", requestID, friendID)}
}

func (_c *MockSocialServiceInterface_AcceptFriendRequest_Call) Run(run func(requestID uuid.UUID, friendID uuid.UUID)) *MockSocialServiceInterface_AcceptFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSocialServiceInterface_AcceptFriendRequest_Call) Return(_a0 *models.Friendship, _a1 error) *MockSocialServiceInterface_AcceptFriendRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialServiceInterface_AcceptFriendRequest_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*models.Friendship, error)) *MockSocialServiceInterface_AcceptFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePost provides a mock function with given fields: userID, tmdbID, mediaType, blurb
func (_m *MockSocialServiceInterface) CreatePost(userID uuid.UUID, tmdbID int, mediaType string, blurb string) (*models.Post, error) {
	ret := _m.Called(userID, tmdbID, mediaType, blurb)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, string, string) (*models.Post, error)); ok {
		return rf(userID, tmdbID, mediaType, blurb)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, string, string) *models.Post); ok {
		r0 = rf(userID, tmdbID, mediaType, blurb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, string, string) error); ok {
		r1 = rf(userID, tmdbID, mediaType, blurb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialServiceInterface_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockSocialServiceInterface_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - userID uuid.UUID
//   - tmdbID int
//   - mediaType string
//   - blurb string
func (_e *MockSocialServiceInterface_Expecter) CreatePost(userID interface{}, tmdbID interface{}, mediaType interface{}, blurb interface{}) *MockSocialServiceInterface_CreatePost_Call {
	return &MockSocialServiceInterface_CreatePost_Call{Call: _e.mock.On("CreatePost", userID, tmdbID, mediaType, blurb)}
}

func (_c *MockSocialServiceInterface_CreatePost_Call) Run(run func(userID uuid.UUID, tmdbID int, mediaType string, blurb string)) *MockSocialServiceInterface_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockSocialServiceInterface_CreatePost_Call) Return(_a0 *models.Post, _a1 error) *MockSocialServiceInterface_CreatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialServiceInterface_CreatePost_Call) RunAndReturn(run func(uuid.UUID, int, string, string) (*models.Post, error)) *MockSocialServiceInterface_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriends provides a mock function with given fields: userID
func (_m *MockSocialServiceInterface) GetFriends(userID uuid.UUID) ([]models.Friendship, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriends")
	}

	var r0 []models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Friendship, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Friendship); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialServiceInterface_GetFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriends'
type MockSocialServiceInterface_GetFriends_Call struct {
	*mock.Call
}

// GetFriends is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockSocialServiceInterface_Expecter) GetFriends(userID interface{}) *MockSocialServiceInterface_GetFriends_Call {
	return &MockSocialServiceInterface_GetFriends_Call{Call: _e.mock.On("GetFriends", userID)}
}

func (_c *MockSocialServiceInterface_GetFriends_Call) Run(run func(userID uuid.UUID)) *MockSocialServiceInterface_GetFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockSocialServiceInterface_GetFriends_Call) Return(_a0 []models.Friendship, _a1 error) *MockSocialServiceInterface_GetFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialServiceInterface_GetFriends_Call) RunAndReturn(run func(uuid.UUID) ([]models.Friendship, error)) *MockSocialServiceInterface_GetFriends_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriendsFeed provides a mock function with given fields: userID
func (_m *MockSocialServiceInterface) GetFriendsFeed(userID uuid.UUID) ([]models.Post, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendsFeed")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Post, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Post); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialServiceInterface_GetFriendsFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriendsFeed'
type MockSocialServiceInterface_GetFriendsFeed_Call struct {
	*mock.Call
}

// GetFriendsFeed is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockSocialServiceInterface_Expecter) GetFriendsFeed(userID interface{}) *MockSocialServiceInterface_GetFriendsFeed_Call {
	return &MockSocialServiceInterface_GetFriendsFeed_Call{Call: _e.mock.On("GetFriendsFeed", userID)}
}

func (_c *MockSocialServiceInterface_GetFriendsFeed_Call) Run(run func(userID uuid.UUID)) *MockSocialServiceInterface_GetFriendsFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockSocialServiceInterface_GetFriendsFeed_Call) Return(_a0 []models.Post, _a1 error) *MockSocialServiceInterface_GetFriendsFeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialServiceInterface_GetFriendsFeed_Call) RunAndReturn(run func(uuid.UUID) ([]models.Post, error)) *MockSocialServiceInterface_GetFriendsFeed_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: query
func (_m *MockSocialServiceInterface) SearchUsers(query string) ([]models.User, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.User, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []models.User); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialServiceInterface_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockSocialServiceInterface_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - query string
func (_e *MockSocialServiceInterface_Expecter) SearchUsers(query interface{}) *MockSocialServiceInterface_SearchUsers_Call {
	return &MockSocialServiceInterface_SearchUsers_Call{Call: _e.mock.On("SearchUsers", query)}
}

func (_c *MockSocialServiceInterface_SearchUsers_Call) Run(run func(query string)) *MockSocialServiceInterface_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSocialServiceInterface_SearchUsers_Call) Return(_a0 []models.User, _a1 error) *MockSocialServiceInterface_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialServiceInterface_SearchUsers_Call) RunAndReturn(run func(string) ([]models.User, error)) *MockSocialServiceInterface_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SendFriendRequest provides a mock function with given fields: userID, friendID
func (_m *MockSocialServiceInterface) SendFriendRequest(userID uuid.UUID, friendID uuid.UUID) (*models.Friendship, error) {
	ret := _m.Called(userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for SendFriendRequest")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.Friendship, error)); ok {
		return rf(userID, friendID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.Friendship); ok {
		r0 = rf(userID, friendID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(userID, friendID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialServiceInterface_SendFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendFriendRequest'
type MockSocialServiceInterface_SendFriendRequest_Call struct {
	*mock.Call
}

// SendFriendRequest is a helper method to define mock.On call
//   - userID uuid.UUID
//   - friendID uuid.UUID
func (_e *MockSocialServiceInterface_Expecter) SendFriendRequest(userID interface{}, friendID interface{}) *MockSocialServiceInterface_SendFriendRequest_Call {
	return &MockSocialServiceInterface_SendFriendRequest_Call{Call: _e.mock.On("SendFriendRequest", userID, friendID)}
}

func (_c *MockSocialServiceInterface_SendFriendRequest_Call) Run(run func(userID uuid.UUID, friendID uuid.UUID)) *MockSocialServiceInterface_SendFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSocialServiceInterface_SendFriendRequest_Call) Return(_a0 *models.Friendship, _a1 error) *MockSocialServiceInterface_SendFriendRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialServiceInterface_SendFriendRequest_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*models.Friendship, error)) *MockSocialServiceInterface_SendFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSocialServiceInterface creates a new instance of MockSocialServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocialServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocialServiceInterface {
	mock := &MockSocialServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
